package_overrides:
  convert:
    host: localhost:4000
  cache:
    host: localhost:4001
workflows:
  SlackPostIt:
    triggers:
      webhook:
        response: postIts
        response_content_type: application/json
    vars:
      cacheTemplate : {"type": "mrkdwn","text": "{{range .postItRecords}} {{.category}}: {{.note}}\n\n{{end}}"}
    steps:
      - convert:parse_line@1.0:
          debug: true
          inputs:
            String: ${trigger.body}
            Delimiter: "&"
            StringFields:
              text: 8
          outputs:
            Record: parsedLine
      - convert:parse_line@1.0:
          debug: true
          inputs:
            String: ${parsedLine.text}
            Delimiter: "="
            StringFields:
              Request: 1
          outputs:
            Record: Text
      - convert:targeted_line_parse@1.0:
          debug: true
          inputs:
            String: ${Text.Request}
            Delimiter: "+"
            Indices: 2
            StringFields:
              action: 0
              unparsedSegment: 1
          outputs:
            Record: actionParsed
      - convert:targeted_line_parse@1.0:
          run_if: '${actionParsed.action} == "post"'
          debug: true
          inputs:
            String: ${actionParsed.unparsedSegment}
            Delimiter: "+"
            Indices: 2
            StringFields:
              category: 0
              unparsedNote: 1
          outputs:
            Record: categoryParsed
      - convert:parse_build_string@1.0:
          run_if: '${actionParsed.action} == "post"'
          debug: true
          inputs:
            String: ${categoryParsed.unparsedNote}
            Delimiter: "+"
          outputs:
            NewString: note
      - convert:hash_string@1.0:
          run_if: '${actionParsed.action} == "post"'
          debug: true
          inputs:
            note: ${note}
            category: ${categoryParsed.category}
          outputs:
            Record: record
            Hash: hashedNote
      - cache:push@1.0:
          run_if: '${actionParsed.action} == "post"'
          debug: true
          inputs:
            Record: ${record}
            Id: ${hashedNote}
            CacheName: 'PostIts'
#      - cache:pull@1.0:
#          run_if: '${actionParsed.action} == "get"'
#          debug: true
#          inputs:
#            Id: ${hashedNote}
#            Category: ${actionParsed.unparsedSegment}
#            CacheName: 'PostIts'
#          outputs:
#            Records: rawPostIts
#            Found: ok
      - cache:pull_bulk@1.0:
          run_if: '${actionParsed.action} == "get"'
          debug: true
          inputs:
            Category: ${actionParsed.unparsedSegment}
            CacheName: 'PostIts'
            Limit: 5
          outputs:
            Records: rawPostIts
            Found: ok
      - convert:set_fields@1.0:
          run_if: '${actionParsed.action} == "get"'
          debug: true
          inputs:
            Fields:
              postItRecords: ${rawPostIts}
          outputs:
            Record: postItJson
      - common:template@1.0:
          run_if: '${actionParsed.action} == "get"'
          debug: true
          inputs:
            Record: ${postItJson}
            Template: ${cacheTemplate.toString()}
          outputs:
            Output: templatedPostIts
      - convert:parse_json_object@1.0:
          run_if: '${actionParsed.action} == "get"'
          debug: true
          inputs:
            String: ${templatedPostIts}
          outputs:
            Record: postIts

# RUNNING & TESTING THE WORKFLOW:
# apptree run workflow -f workflows/SlackPostIt/workflow.yaml --id SlackPostIt
# apptree publish workflow -f workflows/SlackPostIt/workflow.yaml -project surfrating.commandinghands.com

