# Step meta data:
name: twitter
version: 1.0
runtime: go
exec: main

steps:
  tweet@1.0:
    description: Tweet to twitter as part of your workflow
    inputs:
      Text:
        required: true
        description: "The text you'd like to tweet"
        sample: "Just postin' to Twitter..."
      AccessToken:
        required: true
        description: "Your twitter API account Access Token"
        sample: "jhf78dsfu34fn38faefjasdhkf"
      AccessTokenSecret:
        required: true
        description: "Your twitter API account AccessTokenSecret"
        sample: "jhf78d/lkgjdsfkdsjf ldksjfsfu34fn38faefjasdhkf"
    outputs:
      Success:
        description: "A boolean that tells you if your tweet was successfully
          posted."
