name: convert
version: 1.0
lang: go
executables:
  linux:
    amd64: main_linux_amd64
  darwin:
    amd64: main_darwin_amd64
  windows:
    amd64: main_windows_amd64.exe
steps:
  parse_json_object@1.0:
    inputs:
      String:
        required: true
        description: The string to parse into a json object
        samp: '{"key" : "value"}'
    outputs:
      Record:
        description: The json object
  map_records@1.0:
    inputs:
      From:
        required: true
        description: The json record to map to a new record
      MapValues:
        required: true
        description: A json object of the field mappings
    outputs:
      To:
        description: The json record to return
  set_fields@1.0:
      inputs:
        Record:
          required: false
          description: the json object to add the given fields to
        Fields:
          required: true
          description: the fields to add to the record
      outputs:
        Record:
          description: the record with the fields added
  extract_fields@1.0:
      inputs:
        Record:
          required: true
          description: the record you would like to extract fields from
        Fields:
          required: true
          description: the fields to extract to returned record
      outputs:
        Record:
          description: the record with the fields extracted
  parse_line@1.0:
    inputs:
      String:
        required: true
        description: The line of text you want to parse
        sample: "Field1|Field2|Field3"
      Delimiter:
        required: true
        description: Delimiter used to separate the fields
        sample: "|"
      StringFields:
        required: false
        description: A list of fields to parse as a string. The field name you want to parse out should be on the left, the index of the field on the right
        sample: |
          FieldA: 1
          FieldB: 2
      IntFields:
        required: false
        description: A list of fields to parse as an int. The field name you want to parse out should be on the left, the index of the field on the right
        sample: |
          FieldA: 1
          FieldB: 2
      FloatFields:
        required: false
        description: A list of fields to parse as an float. The field name you want to parse out should be on the left, the index of the field on the right
        sample: |
          FieldA: 1
          FieldB: 2
    outputs:
      Record:
        description: An object containing the parsed fields
