name: webhook
version: 1.0
lang: go
exec: main
webhook_get@1.0:
  description: Performs a GET webhook
  inputs:
    Url:
      required: true
      description: ""
      sample:
  outputs:
    ResponseBody:
      description: ""
      sample:
  webhook_post@1.0:
    description: Posts a webhook
    inputs:
      Body:
        required: true
        description: ""
      ContentType:
        required: true
        description: ""
      Url:
        required: true
        description: ""
    outputs:
      ResponseBody:
        description: ""
