name: filesystem
version: 1.0
lang: go

executables:
  linux:
    amd64: main_linux_amd64
  darwin:
    amd64: main_darwin_amd64
  windows:
    amd64: main_windows_amd64.exe

steps:
  file_read_lines@1.0:
    inputs:
      FilePath:
        required: true
        description: The local file path that you would like to parse.
      FieldNames:
        required: false
        description: The field names that will be used in mapping each line to an object. Can be omitted if using headers as field names.
      UseHeaderAsFieldNames:
        required: true
        description: A flag indicating whether or not field names are being passed in or parsed from the file headers.
      FieldDelimiter:
        required: true
        description: The string delimiter used to separate fields in a line
    outputs:
      Records:
        description: Each line of the file as a list of map objects
  list_directory_contents@1.0:
    inputs:
      DirectoryPath:
        required: true
        description: The local file path that you would like to parse.
    outputs:
      Files:
        description: A list of the files and directories found
  read_lines_and_queue@1.0:
    inputs:
      FilePath:
        required: true
        description: The local file path that you would like to parse.
      FieldNames:
        required: false
        description: The field names that will be used in mapping each line to an object. Can be omitted if using headers as field names.
      UseHeaderAsFieldNames:
        required: true
        description: A flag indicating whether or not field names are being passed in or parsed from the file headers.
      FieldDelimiter:
        required: true
        description: The string delimiter used to separate fields in a line
      Workflow:
        required: true
        description: The workflow that you want to queue up
    outputs: {}
