name: google_sheets
version: 1.0

runtime: go #the language the package is in

#The executable name within this package
exec: main

#The steps in this package
steps:
  google_sheets_read@1.0:
    description: Read from a google sheet
    inputs:
      SpreadsheetId:
        required: true
        description: "The ID of the Google Spreadsheet"
        sample: XD23223211212
      SheetIndex:
        required: false
        description: "The index of the sheet you want to use. Defaults to the first sheet."
        sample: 0
      Credentials:
        required: true
        description: "Your Google Sheets credentials JSON. To create your credentials see https://developers.google.com/sheets/api/quickstart/go"
        sample: '{}'
      Fields:
        required: true
        description: "The names of the fields in the order they are defined within the spreadsheet"
        sample: |
          - firstName
          - lastName
          - email
    outputs:
      Rows:
        description: "The output of each row"