# Step meta data:
name: script
version: 1.0
runtime: go
executables:
  linux:
    amd64: main_linux_amd64
  darwin:
    amd64: main_darwin_amd64
  windows:
    amd64: main_windows_amd64.exe

steps:
  js@1.0:
    description: run javascript
    inputs:
      Script:
        required: true
        description: "the script you'd like to run written in java script"
      ScriptVars:
        required: true
        description: "a map of values you'd like to make available as variables in your script"
    outputs:
      ReturnValue:
        description: "The value returned from your script"