name: postgres
version: 1.0
lang: go
exec: main
windows_exec: main
steps:
  insert_batch@1.0:
    description: "Accepts a list of records and inserts them into a database."
    inputs:
      Sql:
        required: true
        description: "The insert statement you'd like to perform"
        sample: "INSERT INTO my_table VALUES ($1,$2)"
      Records:
        required: true
        description: "The list of records you'd like to insert"
        sample: myvar
      ValueFields:
        required: true
        description: "The field names you'd like to pull from from the `Records` input."
        sample: |
          - firstName
          - lastName
  query@1.0:
    description: "Performs a SELECT query"
    inputs:
      ConnectionString:
        required: true
        sample: "postgres://user:passw@localhost:5432"
        description: "Postgres Connection string"
      Sql:
        required: true
        description: ""
    outputs:
      Results:
        description: "The records returned from the query."